project:
  type: website
  output-dir: docs

website:
  title: "IML"
  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - section: "Theory"
        contents: "th/*"
      - section: "Laboratory"
        contents: "lab/*"
      - section: "Exams"
        contents: "exams/*"


format:
  html:
    page-layout: full
    toc: true