project:
  type: website
  output-dir: docs

website:
  title: "IML"
  sidebar:
    style: docked
    contents:
      - section: "Theory"
        contents: "th/*"
      - section: "Exams"
        contents: "exams/*"

format:
  html:
    page-layout: full
    toc: true